name: "Update Docker Image"

on:
  push:
    branches: ["master"]
  schedule:
    - cron: 59 23 * * 0
  workflow_dispatch:

jobs:
  publish:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: branch

      - name: Derive docker hub repo name
        id: repo_name
        shell: bash
        run: |
          REGEX="/(.+)"
          [[ "${{ github.repository }}" =~ $REGEX ]]
          DOCKER_HUB_REPO=${BASH_REMATCH[1]}
          echo "docker_hub_repo=$DOCKER_HUB_REPO" >> $GITHUB_OUTPUT

      - name: Get commit sha
        id: sha
        run: echo "short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Check out the git repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            digiserve/${{ steps.repo_name.outputs.docker_hub_repo }}:${{ steps.branch.outputs.branch }}
            digiserve/${{ steps.repo_name.outputs.docker_hub_repo }}:${{ steps.sha.outputs.short }}
